steps:
  build:
    image: node:20
    commands:
      - npm ci
      - npm run build

  lighthouse:
    image: node:20
    commands:
      - npm ci
      - node lighthouse-audit.js

  docker-build:
    image: docker:27
    pull: true
    commands:
      - docker build --no-cache -t nemesisguy/nemesisnet:dev .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [push, tag, manual]

  docker-push:
    image: docker:27
    pull: true
    commands:
      - docker push nemesisguy/nemesisnet:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [push, tag, manual]
      branch: main