version: "3.9"

services:
  nemesisnet-dev:
    image: nemesisguy/nemesisnet:dev
    container_name: nemesisnet-dev
    restart: unless-stopped
    ports:
      - "9114:3000"
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}
      - TURNSTILE_SITE_KEY=${TURNSTILE_SITE_KEY}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}